[build]
  publish = "build"
  command = "yarn run build"

[build.environment]
  RUBY_VERSION = "2.6.2"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
